# Generated by Django 5.0.4 on 2024-06-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_categoriesmodel_ordermodel_productsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='restaurantId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='type',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='userId',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
