# Generated by Django 5.0.4 on 2024-04-26 07:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_categoriesmodel_productsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesmodel',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
