# Generated by Django 5.0.4 on 2024-04-26 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_categoriesmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriesmodel',
            name='image',
        ),
    ]
