# Generated by Django 5.0.4 on 2024-04-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_categoriesmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesmodel',
            name='image',
            field=models.ImageField(default='category-default.webp', upload_to='img/categories'),
        ),
    ]
