# Generated by Django 5.0.4 on 2024-06-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_productsmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='image',
            field=models.ImageField(default='img/products/product-default.webp', upload_to='img/products/'),
        ),
    ]
