# Generated by Django 5.0.4 on 2024-06-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_productsmodel_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(default=None, max_length=100)),
                ('type', models.CharField(default=None, max_length=100)),
                ('restaurantId', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=None)),
                ('price', models.IntegerField(default=1)),
                ('products', models.CharField(max_length=100)),
                ('cookingTime', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='image',
            field=models.ImageField(default='img/products/product-default.webp', upload_to='img/products/'),
        ),
    ]
