# Generated by Django 5.0.4 on 2024-06-20 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_productsmodel_image'),
        ('menu', '0009_ordermodel_alter_productsmodel_image'),
    ]

    operations = [
    ]
