# Generated by Django 5.0.4 on 2024-06-20 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_merge_20240620_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
