# Generated by Django 5.0.4 on 2024-06-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_ordermodel_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='cookingTime',
            field=models.IntegerField(default=0),
        ),
    ]
